identidock:
  build: .
  ports:
#    - "9090:9090"
#    - "9191:9191"
    - "5000:5000"
  environment:
#    ENV: PRO
    ENV: DEV
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:latest
